name: Check

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: check and test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run check
      - run: pnpm run test
